# -*- coding: utf-8 -*-
"""RED

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rosb63fWWkSVh_byU5ikiBe_p1iUMOo
"""

#RED #SANJAY S #PSG #Newsfeed

def generate_data_science_roadmap():
    roadmap = [
        "Introduction to Data Science",
        "Purpose of Learning and Applications",
        "Mathematics and Statistics for Data Science",
        "Programming in Python",
        "Data Cleaning and Preprocessing",
        "Exploratory Data Analysis",
        "Data Visualization",
        "Machine Learning Fundamentals",
        "Advanced Machine Learning",
        "Big Data and Cloud Computing",
        "Deep Learning",
        "Natural Language Processing",
        "Data Science Projects",
    ]
    return roadmap

def generate_python_roadmap():
    roadmap = [
        "Introduction to Python",
        "Purpose of Learning and Applications",
        "Python Basics and Syntax",
        "Control Flow and Loops",
        "Functions and Modules",
        "File Handling",
        "Data Structures (Lists, Tuples, Dictionaries, Sets)",
        "Object-Oriented Programming",
        "Error Handling and Debugging",
        "Intermediate Python Concepts",
        "Python Libraries (numpy, pandas, matplotlib, etc.)",
        "Python Projects",
    ]
    return roadmap

def generate_web_development_roadmap():
    roadmap = [
        "Introduction to Web Development",
        "Purpose of Learning and Applications",
        "HTML Fundamentals",
        "CSS Fundamentals",
        "Responsive Web Design",
        "CSS Grid and Flexbox",
        "JavaScript Basics",
        "DOM Manipulation",
        "Event Handling",
        "AJAX and APIs",
        "Front-End Frameworks (e.g., React, Vue)",
        "Back-End Development (e.g., Node.js, Django, Flask)",
        "Version Control with Git",
        "Web Development Projects",
    ]
    return roadmap
def generate_business_analyst_roadmap():
    roadmap = [
        "Introduction to Business Analysis",
        "Purpose of Learning and Applications",
        "Business Analysis Frameworks and Methodologies",
        "Understanding Business Processes",
        "Requirements Elicitation and Gathering",
        "Data Analysis and Interpretation",
        "Creating Use Cases and User Stories",
        "Business Process Modeling",
        "Stakeholder Management",
        "Communication and Documentation Skills",
        "Domain Knowledge (Industry-Specific)",
        "Tools for Business Analysis (e.g., Excel, SQL)",
        "Project Management Basics",
        "Agile and Scrum Practices",
        "Testing and Quality Assurance",
        "Risk Analysis and Management",
        "Presentation and Reporting Skills",
        "Professional Ethics and Conduct",
        "Business Analysis Certification (Optional)",
        "Advanced Topics in Business Analysis",
    ]
    return roadmap

def generate_game_development_roadmap():
    roadmap = [
        "Introduction to Game Development",
        "Purpose of Learning and Applications",
        "Understanding Game Genres and Mechanics",
        "Programming Fundamentals (e.g., C++, C#)",
        "Game Engines (e.g., Unity, Unreal Engine)",
        "Graphics and Visual Effects",
        "Game Physics and Simulations",
        "User Interface (UI) and User Experience (UX) Design",
        "3D Modeling and Animation",
        "Game Sound Design and Music",
        "Level Design and Environment Creation",
        "Gameplay Scripting and Logic",
        "Multiplayer and Network Programming",
        "Game Testing and Quality Assurance",
        "Monetization Strategies and In-Game Purchases",
        "Publishing and Distribution Platforms",
        "Marketing and Promotion for Games",
        "Continuous Learning and Staying Updated",
        "Creating Game Portfolio",
        "Collaboration and Teamwork Skills",
        "Personal Projects and Game Jams",
    ]
    return roadmap

def generate_ui_ux_roadmap():
    roadmap = [
        "Introduction to UI/UX Design",
        "Purpose of Learning and Applications",
        "Understanding User-Centered Design",
        "User Research and User Personas",
        "Information Architecture",
        "Wireframing and Prototyping",
        "Visual Design Principles",
        "Typography and Color Theory",
        "Creating UI Elements (Buttons, Icons, etc.)",
        "Responsive and Mobile Design",
        "Interaction Design",
        "Usability Testing and Feedback",
        "User Flows and Journey Mapping",
        "Accessibility and Inclusive Design",
        "Design Tools (e.g., Adobe XD, Sketch, Figma)",
        "Front-End Development Basics",
        "Collaboration with Developers",
        "Portfolio Creation and Presentation",
        "Continuous Learning and Staying Updated",
        "Freelancing and Client Communication",
        "Building a Personal Brand",
    ]
    return roadmap

def generate_r_programming_roadmap():
    roadmap = [
        "Introduction to R Programming",
        "Purpose of Learning and Applications",
        "R Basics and Syntax",
        "Data Types and Variables",
        "Vectors, Matrices, and Arrays",
        "Data Frames and Lists",
        "Control Flow and Loops",
        "Functions and Packages",
        "Data Visualization with ggplot2",
        "Data Import and Export",
        "Data Manipulation with dplyr",
        "Statistical Analysis with R",
        "Hypothesis Testing and ANOVA",
        "Linear Regression",
        "Logistic Regression",
        "Time Series Analysis",
        "Machine Learning with R",
        "Text Mining and Natural Language Processing",
        "Visualization with Shiny",
        "Version Control with Git",
        "Collaboration in R Projects",
        "Creating R Packages",
    ]
    return roadmap
def generate_sql_roadmap():
    roadmap = [
        "Introduction to Databases",
        "Purpose of Learning and Applications",
        "Basic SQL Syntax",
        "SELECT Statement",
        "Filtering and Sorting Data",
        "Aggregate Functions",
        "Joins and Subqueries",
        "Table Creation and Data Types",
        "Data Modification (INSERT, UPDATE, DELETE)",
        "Indexes and Performance Optimization",
        "Normalization and Database Design",
        "Views and Stored Procedures",
        "Transactions and Concurrency",
        "Advanced Query Techniques",
        "Window Functions",
        "Common Table Expressions (CTEs)",
        "Triggers and Events",
        "Database Security and User Permissions",
        "Backup and Recovery Strategies",
        "Working with NoSQL Databases (Optional)",
        "Data Warehousing Concepts (Optional)",
        "Real-world Projects and Practice",
    ]
    return roadmap

def generate_mongodb_roadmap():
    roadmap = [
        "Introduction to NoSQL Databases",
        "Purpose of Learning and Applications",
        "Understanding MongoDB and Document Databases",
        "Installing and Setting Up MongoDB",
        "Basic CRUD Operations",
        "Querying and Filtering Data",
        "Indexes and Performance Optimization",
        "Aggregation Framework",
        "Data Modeling in MongoDB",
        "Embedding and Referencing Data",
        "Transactions and Concurrency",
        "Data Validation and Schema Design",
        "Geospatial Data and Indexing",
        "Text Search and Full-Text Indexes",
        "Replication and High Availability",
        "Sharding and Scalability",
        "Security and User Authentication",
        "Backup and Disaster Recovery",
        "Working with MongoDB Atlas (Cloud Service)",
        "MongoDB Drivers and Client Libraries",
        "Real-world Projects and Practice",
        "Monitoring and Performance Tuning",
    ]
    return roadmap
def generate_java_roadmap():
    roadmap = [
        "Introduction to Java",
        "Purpose of Learning and Applications",
        "Setting Up Java Development Environment",
        "Java Syntax and Basic Concepts",
        "Data Types and Variables",
        "Control Flow (if, switch, loops)",
        "Functions and Methods",
        "Object-Oriented Programming (OOP)",
        "Classes and Objects",
        "Inheritance and Polymorphism",
        "Interfaces and Abstract Classes",
        "Exception Handling",
        "File I/O and Streams",
        "Collections Framework",
        "Generics",
        "Multithreading and Concurrency",
        "Lambda Expressions",
        "Java Streams",
        "JavaFX for User Interfaces",
        "Database Connectivity with JDBC",
        "Web Development with Servlets and JSP",
        "Spring Framework Basics (Optional)",
        "Building RESTful APIs (Optional)",
        "Testing with JUnit",
        "Version Control with Git",
        "Java Coding Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap
def generate_php_roadmap():
    roadmap = [
        "Introduction to PHP",
        "Purpose of Learning and Applications",
        "Setting Up PHP Development Environment",
        "PHP Syntax and Basic Concepts",
        "Variables and Data Types",
        "Control Structures (if, switch, loops)",
        "Functions and Closures",
        "Arrays and Array Functions",
        "Strings and String Functions",
        "Working with Forms and User Input",
        "File Handling and I/O",
        "Error Handling and Exceptions",
        "PHP Super Globals",
        "Object-Oriented Programming (OOP) in PHP",
        "Classes and Objects",
        "Inheritance and Polymorphism",
        "Interfaces and Abstract Classes",
        "Traits and Namespaces",
        "Database Connectivity with PDO",
        "Sessions and Cookies",
        "Web Security Best Practices",
        "Working with JSON and XML",
        "Web Development with PHP",
        "Creating RESTful APIs",
        "Using Composer for Package Management",
        "Testing with PHPUnit",
        "Version Control with Git",
        "PHP Coding Standards and Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap



def generate_kotlin_roadmap():
    roadmap = [
        "Introduction to Kotlin",
        "Purpose of Learning and Applications",
        "Setting Up Kotlin Development Environment",
        "Kotlin Basics and Syntax",
        "Variables and Data Types",
        "Control Flow (if, when, loops)",
        "Functions and Lambdas",
        "Nullable Types and Null Safety",
        "Collections and Functional Programming",
        "Object-Oriented Programming (OOP) in Kotlin",
        "Classes and Objects",
        "Inheritance and Polymorphism",
        "Interfaces and Abstract Classes",
        "Data Classes and Sealed Classes",
        "Extensions and Extension Functions",
        "Type Aliases and Inline Classes",
        "Standard Library Functions",
        "Functional Programming with Kotlin",
        "Coroutines for Asynchronous Programming",
        "Generics and Type Variance",
        "Annotations and Reflection",
        "Database Interaction with Kotlin",
        "Web Development with Kotlin (e.g., Ktor)",
        "Android App Development with Kotlin",
        "Dependency Injection with Koin or Dagger",
        "Testing with JUnit and MockK",
        "Version Control with Git",
        "Kotlin Coding Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap

def generate_c_roadmap():
    roadmap = [
        "Introduction to C Programming",
        "Setting Up C Development Environment",
        "C Basics and Syntax",
        "Variables and Data Types",
        "Control Flow (if, switch, loops)",
        "Functions and Pointers",
        "Arrays and Strings",
        "Structures and Unions",
        "Memory Management and Dynamic Allocation",
        "File Handling and I/O",
        "Preprocessor Directives",
        "Bit Manipulation",
        "Recursion and Backtracking",
        "Sorting and Searching Algorithms",
        "Data Structures (e.g., Linked Lists, Stacks, Queues)",
        "Pointers to Functions and Callbacks",
        "Multi-dimensional Arrays",
        "Error Handling and Debugging",
        "Understanding and Using Libraries",
        "Creating Makefiles",
        "Understanding Assembly Language and Low-level Concepts",
        "Concurrency and Multithreading (Optional)",
        "Networking and Sockets (Optional)",
        "Version Control with Git",
        "C Coding Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap
def generate_cplusplus_roadmap():
    roadmap = [
        "Introduction to C++",
        "Setting Up C++ Development Environment",
        "C++ Basics and Syntax",
        "Variables and Data Types",
        "Control Flow (if, switch, loops)",
        "Functions and Function Overloading",
        "Pointers and References",
        "Memory Management (Dynamic Allocation)",
        "Object-Oriented Programming (OOP) in C++",
        "Classes and Objects",
        "Constructors and Destructors",
        "Inheritance and Polymorphism",
        "Operator Overloading",
        "Templates and Generic Programming",
        "STL (Standard Template Library)",
        "Exception Handling",
        "File I/O and Streams",
        "Smart Pointers",
        "Concurrency with Threads",
        "Lambda Expressions",
        "Design Patterns in C++",
        "Networking and Sockets (Optional)",
        "OpenGL for Graphics Programming (Optional)",
        "Version Control with Git",
        "C++ Coding Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap
def generate_swift_roadmap():
    roadmap = [
        "Introduction to Swift",
        "Setting Up Swift Development Environment",
        "Swift Basics and Syntax",
        "Variables and Data Types",
        "Control Flow (if, switch, loops)",
        "Functions and Closures",
        "Optionals and Error Handling",
        "Collections and Enumerations",
        "Structures and Classes",
        "Inheritance and Polymorphism",
        "Protocols and Protocol-Oriented Programming",
        "Generics",
        "Memory Management",
        "Value Types vs. Reference Types",
        "Access Control",
        "Concurrency with Grand Central Dispatch",
        "Working with JSON and REST APIs",
        "Auto Layout and User Interfaces",
        "Model-View-Controller (MVC) Architecture",
        "Core Data for Data Persistence",
        "UIKit and App Development",
        "SwiftUI for Cross-Platform UI Development",
        "Unit Testing and UI Testing",
        "Dependency Management with Swift Package Manager",
        "Version Control with Git",
        "Swift Coding Best Practices",
        "Real-world Projects and Practice",
    ]
    return roadmap
def generate_perl_roadmap():
    roadmap = [
        "Introduction to Perl",
        "Setting Up Perl Development Environment",
        "Perl Basics and Syntax",
        "Scalars, Arrays, and Hashes",
        "Control Flow (if, switch, loops)",
        "Subroutines and Functions",
        "Regular Expressions",
        "File Handling and I/O",
        "String Manipulation",
        "References and Complex Data Structures",
        "Object-Oriented Programming (OOP) in Perl",
        "Packages and Modules",
        "Error Handling and Warnings",
        "Built-in Functions and Pragmas",
        "Working with Files and Directories",
        "Database Connectivity with DBI",
        "Networking and Sockets",
        "Web Development with Perl (e.g., CGI, Catalyst)",
        "Testing with Test::Simple and Test::More",
        "Version Control with Git",
        "Perl Coding Best Practices",
        "CPAN (Comprehensive Perl Archive Network)",
        "Regularly Updated Perl Community and Resources",
        "Real-world Projects and Practice",
    ]
    return roadmap
def main():
    print("Welcome to Red!")
    print("Select a course:")
    print("1. Data Science")
    print("2. Python")
    print("3. Web Development (HTML, CSS, JavaScript)")
    print("4. Business Analyst")
    print("5. Game Development")
    print("6. Ui/Ux")
    print("7. R Programing")
    print("8. Sql")
    print("9.MongoDB")
    print("10.Java")
    print("11.Php")
    print("12.Kotlin")
    print("13.C")
    print("14.C++")
    print("15.Swift")
    print("16.Perl")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        roadmap = generate_data_science_roadmap()
    elif choice == 2:
        roadmap = generate_python_roadmap()
    elif choice == 3:
        roadmap = generate_web_development_roadmap()
    elif choice == 4:
        roadmap = generate_business_analyst_roadmap()
    elif choice == 5:
        roadmap = generate_game_development_roadmap()
    elif choice == 6:
        roadmap = generate_ui_ux_roadmap()
    elif choice == 7:
        roadmap = generate_r_programming_roadmap()
    elif choice == 8:
        roadmap =generate_sql_roadmap()
    elif choice == 9:
        roadmap =generate_mongodb_roadmap()
    elif choice == 10:
        roadmap =generate_java_roadmap()
    elif choice == 11:
        roadmap =generate_php_roadmap()
    elif choice == 12:
        roadmap =generate_kotlin_roadmap()
    elif choice == 13:
        roadmap =generate_c_roadmap()
    elif choice == 14:
        roadmap =generate_cplusplus_roadmap()
    elif choice == 15:
        roadmap =generate_swift_roadmap()
    elif choice == 16:
        roadmap =generate_perl_roadmap()
    else:
        print("Invalid choice. Please select a valid option.")
        return

    print("\nRoadmap for your selected course:")
    for index, topic in enumerate(roadmap, start=1):
        print(f"{index}. {topic}")

if __name__ == "__main__":
    main()

